### ISSUE TITLE
Modificar contenidos de la plantilla

### ISSUE THREAD

**Issue by adrianhdezm** [agora2/agora2.github.io#2]
Aquí podemos discutir los contenidos que queremos poner en la plantilla. 

- [ ] Traducir los contenidos al espñol

**Comment by diazmendez** [comment]
Ok, aquí va la primera propuesta.

(Los documentos para download se han subido al directorio DocsToDownload/)

Sugerencias de contenido:

--- Cambiar el título de "Agora2" a "Ágora 2". Y debajo o entre paréntesis "proyecto en construcción"

--- Cambiar "About Team FAQ" por "Proyecto Equipo Preguntas y respuestas"

--- En el lugar de "Fast in every..." poner el exergo que aparece en el artículo: <<[. . . ] la gente en las ventanas y la muchedumbre [. . . ] saludaron en la república nueva el poder de someter la ambición noble a la voluntad general y acallar ante el veto de la patria la convicción misma, fanática o previsora, del modo de salvarla. José Martı́, Patria (1892).>>

--- Debajo poner: "Democracia 2.0 para la circunscripción" y un link al pdf en espanol con el texto "leer nuestro texto fundacional"

--- A la izquierda poner algo así como: "Nuestro equipo quiere crecer! Buscamos miembros y colaboradores en todos los campos: disenho, programación, asesoramiento, apoyo territorial... Lea nuestro código de conducta (aquí un link) y escríbanos a admin@agora2.org con su disposición"

--- En la sección about, que ahora es Proyecto, los tres puntos Speed..., Nothing... y Grow... se sustituyen por:

	* Lo que es Ágora 2
	Ágora 2 es una plataforma interactiva para asistir al ciudadano en el proceso eleccionario de nivel municipal en la República de Cuba que se diseña explotando convenientemente la armonı́a entre los elementos esenciales de la llamada democracia 2.0 y las caracterı́sticas participativas del proceso eleccionario municipal cubano. La idea es organizar la discusión polı́tica en la red, agrupando los actores según las estructuras territoriales electorales, en las que sus nominaciones y votos tendrán poder real al momento de las asambleas de nominación y el posterior sufragio.

	* Lo que Ágora 2 no es
	1. Ágora 2 no responde a ningún sistema ideológico particular, si bien respeta lo que esté explı́citamente regulado al respecto en la constitución de la República de Cuba.
	2. Ágora 2 no es un sistema electoral paralelo ni de propaganda electoral, se limitará solo a ser un sistema de información y debate interactivo para el elector.
	3. Ágora 2 no obtiene financiamiento de ninguna fuente que no sean personas naturales con derecho al voto en Cuba, en contribuciones voluntarias, reguladas y transparentes.
	
	* Funcionamiento de Ágora 2
	Cualquier ciudadano cubano con derecho al voto podrá conectarse desde internet a la página o la app de la plataforma y buscar su circunscripción. Allí se establecerá un debate, igual al que existe o debiera existir en los barrios. Existirá un sistema de apoyo a nominaciones, de promoción de debate, interacción y validación decriterios, elección de ideas, etc. Habrán cuentas de observador que permitirán participar en los debates. Las reglas del debate garantizarán que todas las opiniones tengan espacio y respeto.


--- En la sección de Preguntas y respuestas:

	* Quién ideó y quién financia este proyecto?
	Ágora 2 es una idea de que nace de un debate entre sus fundadores, ciudadanos cubanos, sin mediación, motivación o injerencia de ninguna otra instancia, nacional o extranjera. Su financiamiento provendrá exclusivamente de ciudadanos cubanos con derecho al voto, y el dinero se usará para pagar los servicios de la web. El equipo trabajará siempre de forma voluntaria y no remunerada.

	* Cómo puedo ayudar?
	Hay tres formas fundamentales de ayudar al proyecto. La primera es como miembro del equipo o como colaborador. Para eso puede enviarnos su disposición via email a la dirección admin@agora2.org o contactar directamente a un miembro del equipo. La segunda es contribuyendo con la divulgación del proyecto a nivel comunitario para motivar la participación popular en los debates de Ágora. Y la tercera es haciendo una donación a la cuenta del proyecto (esta cuenta todavía no existe), que se usará para pagar los servicios de hosting del sitio web. 

	* Qué filiación política tiene Ágora 2?
	Ágora 2 se esforzará en no preferenciar ninguna inclinación política más allá de la observancia estricta de la constitución de la República de Cuba. Como está recogido en nuestro código de conducta, cada miembro del equipo se compromete a que sus sesgos políticos individuales no interfieran con los objetios democráticos del proyecto. La meta es garantizar que todas las opiniones, expresadas adecuadamente, tengan espacio y respeto.

	* Por qué habrán dos tipos de usuario?
	La plataforma está pensada para los electores, esto es, ciudadanos cubanos con derecho al voto, ellos pueden abrir una cuenta de tipo Elector y tener acceso a todas las funcionalidades de Ágora 2. Adicionalmente, las cuentas de tipo Observador están pensadas para usuarios que, sin formar parte activa del proceso eleccionario, quieran participar observando el proceso e interviniendo en los debates. Consideramos que esta posibilidad enriquecerá las discusiones ayudando a contrastar y validar opiniones y puntos de vista.
